### iOS SDK Release
GET https://api.github.com/repos/idlerecord/imqa-ios-sdk/releases
Content-Type: application/json
Accept: application/vnd.github.v3+json
X-GitHub-Api-Version: 2022-11-28
Authorization: Bearer {{$dotenv IDLERECORD_API_RELEASE_TOKEN}}

### Android SDK Release
GET https://api.github.com/repos/idlerecord/the-next-android-sdk/releases
Content-Type: application/json
Accept: application/vnd.github.v3+json
X-GitHub-Api-Version: 2022-11-28
Authorization: Bearer {{$dotenv IDLERECORD_API_RELEASE_TOKEN}}

### Web Agent Release
GET https://api.github.com/repos/idlerecord/imqa-js/releases
Content-Type: application/json
Accept: application/vnd.github.v3+json
X-GitHub-Api-Version: 2022-11-28
Authorization: Bearer {{$dotenv IDLERECORD_API_RELEASE_TOKEN}}
