name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
env:
  NODE_VERSION: '22.x'
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_0A0B46A00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: '' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          NEXT_PUBLIC_LIBNAME_DOTSUFFIX_LABEL: ${{ env.NEXT_PUBLIC_LIBNAME_DOTSUFFIX_LABEL }}
          NEXT_PUBLIC_LIBNAME: ${{ env.NEXT_PUBLIC_LIBNAME }}
          NEXT_PUBLIC_LIBNAME_SHORT: ${{ env.NEXT_PUBLIC_LIBNAME_SHORT }}
          NEXT_PUBLIC_URL: ${{ env.NEXT_PUBLIC_URL }}
          IDLERECORD_API_RELEASE_TOKEN: ${{ secrets.IDLERECORD_API_RELEASE_TOKEN }}
          MDX: ${{ env.MDX }}
          EDIT_BASEURL: ${{ env.EDIT_BASEURL }}
          MDX_BASEURL: ${{ env.MDX_BASEURL }}
          SOURCECODE_BASEURL: ${{ env.SOURCECODE_BASEURL }}
          GITHUB: ${{ env.GITHUB }}
          THEME_PRIMARY: ${{ env.THEME_PRIMARY }}
          THEME_SCHEMA: ${{ env.THEME_SCHEMA }}
          THEME_CONTRAST: ${{ env.THEME_CONTRAST }}
          THEME_NOTE: ${{ env.THEME_NOTE }}
          THEME_TIP: ${{ env.THEME_TIP }}
          THEME_IMPORTANT: ${{ env.THEME_IMPORTANT }}
          THEME_WARNING: ${{ env.THEME_WARNING }}
          THEME_CAUTION: ${{ env.THEME_CAUTION }}
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_0A0B46A00 }}
          action: 'close'
          app_location: '/' # App source code path
