# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - imqa-docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        env:
          NEXT_PUBLIC_LIBNAME_DOTSUFFIX_LABEL: ${{ env.NEXT_PUBLIC_LIBNAME_DOTSUFFIX_LABEL }}
          NEXT_PUBLIC_LIBNAME: ${{ env.NEXT_PUBLIC_LIBNAME }}
          NEXT_PUBLIC_LIBNAME_SHORT: ${{ env.NEXT_PUBLIC_LIBNAME_SHORT }}
          NEXT_PUBLIC_URL: ${{ env.NEXT_PUBLIC_URL }}
          IDLERECORD_API_RELEASE_TOKEN: ${{ secrets.IDLERECORD_API_RELEASE_TOKEN }}
          MDX: ${{ env.MDX }}
          EDIT_BASEURL: ${{ env.EDIT_BASEURL }}
          MDX_BASEURL: ${{ env.MDX_BASEURL }}
          SOURCECODE_BASEURL: ${{ env.SOURCECODE_BASEURL }}
          GITHUB: ${{ env.GITHUB }}
          THEME_PRIMARY: ${{ env.THEME_PRIMARY }}
          THEME_SCHEMA: ${{ env.THEME_SCHEMA }}
          THEME_CONTRAST: ${{ env.THEME_CONTRAST }}
          THEME_NOTE: ${{ env.THEME_NOTE }}
          THEME_TIP: ${{ env.THEME_TIP }}
          THEME_IMPORTANT: ${{ env.THEME_IMPORTANT }}
          THEME_WARNING: ${{ env.THEME_WARNING }}
          THEME_CAUTION: ${{ env.THEME_CAUTION }}
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_757D3D42EB45421383D076A0680CAD0A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1F8E2B323DF940D89C50AC6F5035EA63 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_73ECED5819E54F3BAB7A9CB280AD2256 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'imqa-docs'
          slot-name: 'Production'
          package: .
